### ISSUE TITLE
三维地形在1.76版本cesium中加载报错

### ISSUE THREAD

**Issue by alalashizi** [ngcc-tdt/demo#14]
使用demo中提供的cesiumTdt插件进行地形添加时控制台报错，cesium版本：1.76，是否是因为插件不适配这个版本的cesium
控制台报错如下：
![天地图报错](https://user-images.githubusercontent.com/22320842/195258458-e13297ce-0539-4832-b611-d683499b6106.png)

**Comment by ngcc-tdt** [comment]
是的。



国家地理信息公共服务平台（天地图）
***@***.***
 
发件人： alalashizi
发送时间： 2022-10-12 13:36
收件人： ngcc-tdt/demo
抄送： Subscribed
主题： [ngcc-tdt/demo] 三维地形在1.76版本cesium里加载报错 (Issue #14)
使用demo中提供的cesiumTdt插件进行地形添加控制台报错，cesium版本：1.76，是否是因为插件不适配这个版本的cesium
控制台报错如下：

**Comment by alalashizi** [comment]
1、那这个cesiumTdt插件何时才能支持1.76版本的cesium?
2、若我cesium版本不变，仍是1.76，我要怎样使用天地图的三维地形服务？

**Comment by ngcc-tdt** [comment]
抱歉，暂时无法支持



国家地理信息公共服务平台（天地图）
***@***.***
 
发件人： alalashizi
发送时间： 2022-10-13 15:07
收件人： ngcc-tdt/demo
抄送： ngcc-tdt; Comment
主题： Re: [ngcc-tdt/demo] 三维地形在1.76版本cesium中加载报错 (Issue #14)
1、那这个cesiumTdt插件何时才能支持1.76版本的cesium?
2、若我cesium版本不变，仍是1.76，我要怎样使用天地图的三维地形服务？

**Comment by alalashizi** [comment]
那有支持1.76版本cesium的计划吗？如果有的话，可否透露下大致的时间

**Comment by ngcc-tdt** [comment]
抱歉，因经费原因，目前暂无计划。



国家地理信息公共服务平台（天地图）
***@***.***
 
发件人： alalashizi
发送时间： 2022-10-14 09:38
收件人： ngcc-tdt/demo
抄送： ngcc-tdt; Comment
主题： Re: [ngcc-tdt/demo] 三维地形在1.76版本cesium中加载报错 (Issue #14)
那有支持1.76版本cesium的计划吗？如果有的话，可否透露下大致的时间

**Comment by alalashizi** [comment]
感谢回复！

**Comment by sertceps** [comment]
@alalashizi 兄弟，不好意思打扰你，想问下你最后怎么解决的。用了别的方案还是降版本了。

**Comment by SharronTeng** [comment]
> 使用demo中提供的cesiumTdt插件进行地形添加时控制台报错，cesium版本：1.76，是否是因为插件不适配这个版本的cesium 控制台报错如下： ![天地图报错](https://user-images.githubusercontent.com/22320842/195258458-e13297ce-0539-4832-b611-d683499b6106.png)

我的开始也是报这个错，然后引入了bytebuffer.min.js文件，就没报了
